### ISSUE TITLE
Stoped working after server boot 

### ISSUE THREAD

**Issue by OnlineDigitalServices** [jackm/kijiji-manager#1]
I restarted my ubuntu server, and now Kijiji-manager isn't working! 
How can I get it to work again? 
I am a newbie; please walk me through step by step. 

Thank you.

**Comment by jackm** [comment]
You have to make sure that the app is running, otherwise there is no web server to respond to any HTTP requests that you make.
In a terminal/shell, run the `run.py` Python script to start the app again and leave it running.

**Comment by OnlineDigitalServices** [comment]
Thank you. How do I run the run.py in the terminal?

**Comment by jackm** [comment]
> python3: command not found

Is Python installed? It may be called just `python` instead of `python3`, but make sure that it is at least Python 3.6 or greater. Python 2.7 will not work.

If you created a virtualenv when installing the required Python packages for this project, then also make sure that you activate the virtualenv by sourcing the _activate_ script again before running `run.py`. Refer to the project README for details on this.
