### ISSUE TITLE
Images Rotate when creating new ad

### ISSUE THREAD

**Issue by adm-gis** [jackm/kijiji-manager#18]
When creating a new ad, the images are rotated in the wrong direction (even when they are submitted right-side-up).

**Comment by jackm** [comment]
This is likely due to the image's EXIF data (i.e. metadata) indicating that the image should be rotated a certain degree when displaying it, while the "raw" decoded image is actually not right-side-up. My guess is that when an image gets uploaded using Kijiji's API, the EXIF data gets stripped and so when it is displayed on Kijiji's site, it doesn't rotate it as expected.

One workaround to this is to edit the file using an image editor locally, ensure it is rotated the correct way, and then save the file again but strip out all EXIF data when doing so.

**Comment by adm-gis** [comment]
Yup, that made all the difference.  Thanks for all your work, makes selling stuff so much more efficient.
