### ISSUE TITLE
KijijiApiException: Error: Auth token is invalid. Validation of the authentication token in API request failed.

### ISSUE THREAD

**Issue by QwertyCoolMT** [jackm/kijiji-manager#26]
getting this error when posting a new ad
KijijiApiException: Error: Auth token is invalid. Validation of the authentication token in API request failed.

**Comment by jackm** [comment]
I believe this means that your login token as expired. I'm guessing that you originally logged in many days ago and have been using the same token ever since.

I've yet to determine how long Kijiji will keep the token active for before they consider it expired, and perhaps implement a way for it to auto refresh the token when it does.

Could you try logging out and then logging back in again to manually refresh the token?

**Comment by thanksforkijijimanager** [comment]
The API key needs to be updated (same issue as the first issue I ever posted)

https://github.com/jackm/kijiji-manager/issues/23

Worked for me

**Comment by jackm** [comment]
Please update to release [v0.1.8](../releases/tag/v0.1.8)
