### ISSUE TITLE
Example Payload xml file

### ISSUE THREAD

**Issue by botcoder-sys** [jackm/kijiji-manager#40]
I am new to this repository, I am trying to post ads via payload xml file but I have no clue about the syntax of that file. I tried to find the payload example file but I am unable to find it. Can someone please guide me with it. 
Thanks

**Comment by jackm** [comment]
If you are posting a brand new ad I'd suggest using the form in the normal "Post" page (not "Post Manual"). This will post a new ad and save the ad payload to a file for you.

The manual ad posting page was put there in case you still had an ad payload file where the ad didn't yet exist on the Kijiji site (e.g. the ad expired and was automatically removed), and you still wanted a way to post the same ad without having to use the normal ad posting form.

The XML schema for the ad payload is not something that I have formally documented as it is quite extensive and there are a lot of specific values that must be used otherwise it may be rejected by Kijiji and never get posted.

**Comment by botcoder-sys** [comment]
Thank You very much for the detailed answer on XML payload. I really appreciate it.
