### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by prgrm** [jackm/kijiji-manager#49]
Is anyone else unable to log in? I keep getting this error despite entering the correct username and password:

['api-error: Sorry, your username or password is incorrect. Please try again.']

**Comment by thanksforkijijimanager** [comment]
Works fine for me
Just reposted on multiple accounts

**Comment by prgrm** [comment]
I'm unable to log in for some reason. Some times I get the error "Unable to parse text: mismatched tag" and sometimes "['api-error: Sorry, your username or password is incorrect. Please try again.']" 

I tried running the manager in a docker container and same result. It worked perfectly before! Any suggestions?

**Comment by jackm** [comment]
Do you have another Kijiji account that you could try logging in with? I also have no issues logging in.

**Comment by prgrm** [comment]
I tried with another account and it worked!! I can't figure out what the problem is! I changed my password even, in case the symbol in the password caused a problem, but still no dice.  I never had this problem.  Is there a way to debug the login process to get a hint of what the problem is?

**Comment by jackm** [comment]
Does the main site allow you to login with the account; does it give you any feedback?

If you got the error message `Sorry, your username or password is incorrect. Please try again.` there isn't much more debugging that can be done - the Kijiji API rejected your credentials and isn't allowing you to login.

The error `Unable to parse text: mismatched tag` would indicate that the response it received was malformed XML, or perhaps not XML at all which is quite unexpected since the Kijiji API should (assumed) always be responding with an XML reply.

**Comment by prgrm** [comment]
But why would the api reject my credentials?! I can log in using the app and the web site!

**Comment by jackm** [comment]
@prgrm what was the issue?

**Comment by prgrm** [comment]
You were right, something was wrong with my account. I contacted customer support and they reset my account. That solved the problem.
