### ISSUE TITLE
Install issues (Read.me corrections) & venv issues

### ISSUE THREAD

**Issue by golemoak** [jackm/kijiji-manager#5]
I must have missed something in the read me. 
More specifically about the requirements and the venv during install.

1. Requirements: I assume all requirements will be installed automatically
2: 
A. `python -m venv venv` fails
B. `python3 -m venv venv` fails and suggests `python3-venv` install via apt-get
   
I'm looking at the tutorial about venv you sent also. 

(My ENV:)
Linux 18.04
Google Cloud Platform

*Installing python3-venv and doing :
`python3 -m venv venv`
Instead of :
`python -m venv venv`

Does not throw error.

However, the `pip install .` command throws this during install:
```
error: invalid command 'bdist_wheel'
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for kijiji-manager
  Running setup.py clean for kijiji-manager
Failed to build kijiji-manager

```

but finishes on :
```
  Running setup.py install for kijiji-manager ... done
Successfully installed kijiji-manager-0.1.0
```

Another issue I'm facing on Install 2. (from your Read Me):
By copy, do you mean backup?

On step 4 of your install and when I run the code your provided, I get :
`python -m kijiji_manager`
I get : 
`/usr/bin/python: No module named kijiji-manager/`
When I try with 
`python3 -m kijiji_manager`
I get : 
`/usr/bin/python3: No module named kijiji-manager.__main__; 'kijiji-manager' is a package and cannot be directly executed`
When I try any : 
`kijiji-manager`
I get :
`kijiji-manager: command not found`

Unable to proceed. Probably due to faulty install. Please lmk.

**Comment by jackm** [comment]
> 1. Requirements: I assume all requirements will be installed automatically
>    2:
>    A. `python -m venv venv` fails

The `python` command may be symlinked to the Python 2 interpreter and not the Python 3 interpreter on your system. You will need to invoke the Python 3 interpreter. In this case replace all instances of the `python` command with `python3`.

>    B. `python3 -m venv venv` fails and suggests `python3-venv` install via apt-get

I assume you are using a Debian-based Linux system. On some of these systems, the Python "venv" standard library may not be installed by default and so you would have to install the  `python3-venv`  apt package just as it suggests.

> However, the `pip install .` command throws this during install:
> 
> ```
> error: invalid command 'bdist_wheel'
>   
>   error: invalid command 'bdist_wheel'
>   
>   ----------------------------------------
>   Failed building wheel for kijiji-manager
>   Running setup.py clean for kijiji-manager
> Failed to build kijiji-manager
> ```
> 
> but finishes on :
> 
> ```
>   Running setup.py install for kijiji-manager ... done
> Successfully installed kijiji-manager-0.1.0
> ```

This error is because your Python virtual env is missing the Python `wheel` package. This can be installed using `pip install wheel` within your virtual env. If the `wheel` package is already installed, then you likely need to update your `pip` package version using `pip install --upgrade pip`.

> Another issue I'm facing on Install 2. (from your Read Me):
> By copy, do you mean backup?

I mean make a copy of the sample config file, but place that copy within the _instance_ folder with the new file name `kijiji-manager.cfg` - i.e. run this from within repo root dir: `mkdir instance && cp kijiji_manager/kijiji-manager-sample.cfg instance/kijiji-manager.cfg` then edit `instance/kijiji-manager.cfg` with a new random secret.

> On step 4 of your install and when I run the code your provided, I get :
> `python -m kijiji_manager`
> I get :
> `/usr/bin/python: No module named kijiji-manager/`
> When I try with
> `python3 -m kijiji_manager`
> I get :
> `/usr/bin/python3: No module named kijiji-manager.__main__; 'kijiji-manager' is a package and cannot be directly executed`
> When I try any :
> `kijiji-manager`
> I get :
> `kijiji-manager: command not found`

Are you certain that you've activated your Python virtual env before running these? When you are running the `python3` command it is executing the `/usr/bin/python3` binary which is the system Python interpreter not the Python interpreter that is part of the virtual env you created earlier. The system Python interpreter has no knowledge of the `kijiji-manager` package because you installed that package within the virtual env.

**Comment by rockerguy1978** [comment]
@golemoak, I just set this up on a Raspberry pi running Ubuntu in a virtual environment without any issues. Try testing a virtual environment in another project to see if it is your host system or not.

**Comment by EdwardOak** [comment]
Yeah one second, following jackm answer, will test right afterwards.

**Comment by EdwardOak** [comment]
@jackm "Are you certain that you've activated your Python virtual env before running these? When you are running the python3 command it is executing the /usr/bin/python3 binary which is the system Python interpreter not the Python interpreter that is part of the virtual env you created earlier. The system Python interpreter has no knowledge of the kijiji-manager package because you installed that package within the virtual env."

Is there a way to make the the venv use the proper python version and can you add that to your readme (or lead me to troubleshooting this issue?)

Also, I installed wheel and will try re-installing. Perhaps that was my issue. 

@rockerguy1978 I'm happy for you(?)

**Comment by golemoak** [comment]
@jackm Here were my errors:
Wheel wasnt installed during main install
the cfg file in instance was not properly renamed
key was not properly added to the right file (i thought the main sample file was to be renamed and beforhand copied to instance, its the other way around)

One other question, you said the py-venv i created does not support/contain python3, what should I do about that?

**Comment by golemoak** [comment]
I'm closing this entire issue.

**Comment by golemoak** [comment]
Additional comment to jackm:

"You coded a web platform too bro? Look at you go."
