### ISSUE TITLE
Exception with a large number of requests

### ISSUE THREAD

**Issue by igorank** [jackm/kijiji-manager#50]
When I send many login requests in a row, I get the following error:

`KijijiApiException: Unable to parse text: mismatched tag`

No matter which method of the KijijiApi class is called many times in a row (login(), get_profile() or get_ad()), the following exception pops up: 

`raise KijijiApiException(f"Unable to parse text: {errors.messages[e.code]}")`

**Comment by jackm** [comment]
It is likely that you are being rate limited by Kijiji for many login attempts.

How frequently are you attempting to login with your user credentials? The Kijiji API that this app uses is intended to do infrequent logins since once logged in, it returns a user token. This token is valid for a long time (approx. 30 days) and should be used when making all future API calls.
